### ISSUE TITLE
Visualizing mesh edges and vertices

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [rdeits/MeshCat.jl#152]
@rdeits 
1. Is it possible to turn on edges (and control their thickness and color)
2. I know you can render point clouds but is it possible to render mesh vertices (nodes) on a mesh? E.g. as dots of a certain color? 

Perhaps you can point me to more documentation. 

Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@rdeits can you help with the above query? Thanks

**Comment by rdeits** [comment]
Sure, happy to help! I realized that wireframe support wasn't working, but it will be fixed in #163 which should be merged later today. The only limitation is that you have to draw the object three times: once as the object itself, once as a wireframe, and once as a collection of points. I don't know of any way to tell Three.js to render the object both as a solid and as a wireframe at the same time otherwise. 

Fortunately, it's easy to wrap that up as a function, as I've done in that PR. I'm also going to play around with generating proper documentation, since it's overdue.

**Comment by Kevin-Mattheus-Moerman** [comment]
Great @rdeits thanks. I'll test it shortly.

**Comment by Kevin-Mattheus-Moerman** [comment]
I commented over at https://github.com/rdeits/MeshCat.jl/pull/163
