### ISSUE TITLE
Understand why the GitHub CI Windows runner started failing all of a sudden

### ISSUE THREAD

**Issue by ferrolho** [rdeits/MeshCat.jl#236]
Despite corresponding to the same commit, these two pipeline jobs have different outcomes on the Windows runner:
- https://github.com/rdeits/MeshCat.jl/actions/runs/4739284721/jobs/8413967357 (success)
- https://github.com/rdeits/MeshCat.jl/actions/runs/4739284721/jobs/8891545831 (fail)

For now, I will disable this Windows runner.

**Comment by rdeits** [comment]
They did get slightly different package resolutions (e.g. Adapt 3.6.1 vs. Adapt 3.6.2. I don't think Adapt.jl is actually the issue, but maybe some other dependency also changed versions in the time between those runs? The root cause is missing 7z.exe, which I remember seeing on Windows before. 

I think the root cause is that I'm using BinDeps.unpack_cmd. BinDeps.jl is ancient (last release was 3 years ago). I'm sure there's a better way to unpack a `.tar` file in Julia in 2023.
