### ISSUE TITLE
list children or haskey type function for the tree

### ISSUE THREAD

**Issue by Affie** [rdeits/MeshCat.jl#93]
Say I have a Meshcat Visualizer object (vis) with vis[:poses][:x1] and vis[:poses][:x2]

Is there a way to get a list (:x1,:x2) of children for vis[:poses] or a haskey(vis[:poses], :x1) kind of function similar to a Dictionary?  This information in the local object would be nice. 

I would also like to know how to 'getObject' for example the transform of vis[:poses][:x1]?

cc @dehann

**Comment by rdeits** [comment]
So, there's sort of an easy answer, which is that you can inspect the `vis.core.tree` object, which is exactly the tree of objects and associated transforms. But there are a couple of caveats: first, I'm pretty sure I store serialized MsgPack data rather than the Julia objects (that's pretty easy to change but we'd have to make sure it still performs well). Second, I've mostly been thinking about the communication between the Julia side and the Javascript side as one-way, so we'd have to be careful to make sure that traversing the tree in Julia always gives you what's *actually* in the scene, not just what Julia thinks is in the scene.

**Comment by Affie** [comment]
Thanks, the tree part will work for now. You can close this if you want.
